---
- hosts: webservers 
  become: true
  tasks:
    - name: Initiate ansible
      debug:
        msg:  "mvn -f /var/lib/jenkins/workspace/ansible-demo1/pom.xml clean install package"
      delegate_to: localhost
...
