---
- hosts: webservers 
  become: true
  tasks:
    - name: Initiate ansible
      debug:
        msg:  "mvn -f /var/lib/jenkins/workspace/ansible-demo1/pom.xml clean install package"
      delegate_to: localhost
    - name: Start application on {{ansible_hostname}}
      command: mvn -f /var/lib/jenkins/workspace/ansible-demo/pom.xml clean install
      async: 2100
      poll: 0
      register: import_db
    - name: Check if database import is complete
      async_status:
        jid: "{{ import_db.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      delay: 10
      retries: 300
...
