---
- hosts: webservers 
  become: true
  tasks:
    - name: Initiate ansible
      debug:
        msg:  "mvn -f /var/lib/jenkins/workspace/ansible-demo1/pom.xml clean install package"
      delegate_to: localhost
    - name: Start application on {{ansible_hostname}}
      command: wget "http://admin:admin@54.234.95.130:8080/manager/text/start?path=/ansibledemo-0.0.1-SNAPSHOT"
...
