---
- hosts: webservers 
  become: true
  tasks:
    - name: Initiate ansible
      debug:
        msg:  "mvn -f /var/lib/jenkins/workspace/ansible-demo1/pom.xml clean install package"
      delegate_to: localhost
    - name: Deploy the new WAR file to target servers
      copy: src=/var/lib/jenkins/workspace/ansible-demo1/target/ansibledemo-0.0.1-SNAPSHOT.war dest=/home/ubuntu/tomcat/webapps
...
